id: P009339
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC347
  title: 'བོད་ཀྱི་སློབ་གསོའི་ཁ་ཕྱོགས་དང་དགེ་མཚན་གླིང་བ། དུས་རབས་ཀྱི་རྔ་སྒྲ། '
  author: ''
  volumes:
    69bd5c121edb4b8a925797c9207978df:
      image_group_id: I2PD18727
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
